#网站配置
website:
  #网站名
  name: 爱看小说
  #域名
  domain: akxs.org
  #SEO关键词
  keyword: ${website.name},小说,好看的小说,全本小说网,无弹窗小说,全本小说免费
  #SEO描述
  description: ${website.name}与国内各大小说网站独家合作，提供海量的免费小说和全本小说。同时为您推荐热门言情小说、穿越小说、玄幻小说、都市小说等优秀作品。看免费全本小说，首选${website.name}！
  #联系QQ
  qq: 50330690
